Unify stage and patch files
rayyaw/flash-patcher pull request #80
Opened 2024-02-05 14:15 UTC by rayyaw

## Changes
- Unify stage and patch files. This means you can run `exec-binary`, `exec-python`, and `exec-patcher` within a patch file.

## Testing
- Automated testing.

## Related issues
- closes https://github.com/rayyaw/flash-patcher/issues/77

2024-02-07 14:31 UTC, GTcreyon requested changes
Some serious security considerations, and just a couple minor tweaks.

2024-02-07 14:31 UTC, GTcreyon commented on README.md
> +- `--mainfile`: The main file's path within the top level folder.
I feel like "mainfile" is a bit ambiguous. Is there another term we could use for it? "rootfile" or something?

It might even work to just continue calling it "stagefile". It's just that now "stagefile" is a descriptor for the root patch file, rather than a unique type of file in its own right.

Not major, just a consideration.

2024-02-07 14:31 UTC, GTcreyon commented on README.md
> +exec-patch file.patch
Would `patch` perhaps be better than `exec-patch`?
- More concise
- Conveys the same meaning - we're indicating a patchfile to use
- A patch is not an executable file in the traditional sense. More on this in the next comment...

2024-02-07 14:31 UTC, GTcreyon commented on README.md
> +The command looks like this: `exec-python file.py`.
`exec-` makes sense here, because we're actually executing arbitrary code.

I would argue this is actually a security benefit, because it clarifies to the user, "Hey. You're running code here. This could do literally anything."

I could see a case for `run-`, since it has the full word, conveys the same meaning, and is slightly shorter. However, `exec-` sounds slightly scarier, which works well with the aforementioned security consideration.

In a similar vein, I would strongly recommend renaming `exec-binary`, because a significant proportion of users (possibly a majority) do not know that "binary" in this context refers to an executable file. `exec-program`, `exec-file`, `run-exe`, something like that. They're not exactly pretty, but they're scary enough to prompt caution.

There's also an argument to be made for removing binary support entirely. In my eyes, the edge case of "I want to make a patch for my flash game but I don't want to learn Python" is really not worth facilitating when the edge case of "I want to make a trojan that isn't immediately detectable by anyone with basic coding knowledge" would also be made possible. Especially when it would be targeting the demographic of "kids who play browser games in class" [even if those kids are mostly teens now].

You can also still use a python file to execute a binary file. But seeing `subprocess.run` in a python file immediately raises eyebrows and warrants investigation, whereas normalizing the inclusion of binary files in the patch system by default incentivizes complacency, which is no good.

It may also be useful (in a separate PR) to implement a confirmation stage when running the patcher via the CLI. Something like, "This patch contains executable files that run directly on your computer. They are not verified to be safe, and might damage your system. Only run patches from sources that you trust. Are you sure you want to continue?"

2024-02-07 14:31 UTC, GTcreyon commented on flash_patcher/antlr/PatchfileLexer.g4
> +EXEC_PATCHER    : E X E C '-' P A T C H E R;
That's not what the documentation says. Shouldn't this be `exec-patch`?

2024-02-07 14:31 UTC, GTcreyon commented on flash_patcher/parse/patch_visitor.py
> +        """When we encounter a patch file, we should open and process it"""
Prefer docstrings in the imperative mood. e.g. "Open and process a patch file when it is encountered."

https://peps.python.org/pep-0257/

2024-02-07 14:33 UTC, rayyaw commented on README.md
> +The command looks like this: `exec-python file.py`.
1. `exec-file` sounds good
2. Having confirmation for running binary scripts is definitely a good idea, I'll add this in!

2024-02-07 14:47 UTC, rayyaw commented on README.md
> +The command looks like this: `exec-python file.py`.
Noted. Will remove binary file support, and add confirmation for running Python files.

2024-02-08 00:35 UTC, rayyaw commented
LGTM, ship it!

2024-02-08 00:37 UTC, GTcreyon approved these changes

2024-02-08 00:37 UTC, merged